#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

key=$(ynh_string_random --length=32)
ynh_app_setting_set --app=$app --key=key --value=$key

api_key=$(ynh_string_random --length=32)
ynh_app_setting_set --app=$app --key=api_key --value=$api_key

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
#ynh_script_progression "Adding $app's configuration files..."

#ynh_config_add --template=".env" --destination="$install_dir/.env"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_phpfpm

ynh_config_add_nginx

#ynh_config_add_systemd

#yunohost service add "$app" --description="A short description of the app" --log="/var/log/$app/$app.log"

#=================================================
# INSTALL LIBRETIME
#=================================================
ynh_script_progression "Installing $app..."

pushd "$install_dir"
	./install \
	--listen-port $port \
	--storage-path $data_dir \
	--in-place \
	--no-setup-icecast \
	--no-setup-postgresql \
	--no-setup-rabbitmq \
	--allow-remove-essential \
	https://$domain
popd

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_add_config --template="config.yml" --destination="/etc/libretime/config.yml"

pushd "$install_dir"
	ynh_hide_warnings ynh_exec_as_app libretime-api migrate
popd

adduser $app audio

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

systemctl start libretime.target

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
